## Training own Word2Vec

In [1]:
#Defined tokenized sentences as training data
tokenized_sentences = [['Hello','Welcome','to','AI','Program','by','John'],
                       ['Hello','Glad','to','have','you','here'],
                       ['Hello','Welcome','back'],
                       ['Welcome','to','DS','Program','by','John']]

In [2]:
#Training Word2vec model
from gensim.models import Word2Vec

In [3]:
import warnings
warnings.filterwarnings('ignore')

In [4]:
model = Word2Vec(sentences = tokenized_sentences,min_count=1)
#take all the words which has been occured 1 time. If Igive it 2,in this whole vocab, the words which has been occured 2 times only be considered.

In [5]:
print(model) #Size = 100 features/characteristics for one word

Word2Vec(vocab=13, size=100, alpha=0.025)


In [7]:
words = list(model.wv.vocab)
words

['Hello',
 'Welcome',
 'to',
 'AI',
 'Program',
 'by',
 'John',
 'Glad',
 'have',
 'you',
 'here',
 'back',
 'DS']

In [8]:
#I want to see the vector of training
print(model['AI']) #The word training has been rated on 100 different features
#Encoded value for Program

[-4.57580341e-03  1.95529385e-04 -1.06541382e-03  3.48488777e-03
 -2.16961699e-03 -3.21991974e-03 -4.74931626e-03  4.51995619e-03
  2.83560978e-04  2.96337553e-03  1.62608791e-04 -4.61309124e-03
  2.71834782e-03 -4.65261424e-03  2.37224228e-03  4.29659151e-03
 -4.36337804e-03 -7.59984396e-05 -1.46330777e-03 -1.21599098e-03
 -2.82141287e-03  6.32263604e-04  3.61232064e-03 -4.57766233e-04
  9.74148104e-04 -1.09698623e-03 -3.97061789e-03 -2.87761516e-03
  4.36342182e-03  3.57589684e-03 -3.40322335e-03 -4.40898264e-04
  3.12317838e-03 -1.34172756e-03 -3.17008304e-03 -2.51142704e-03
 -1.98264373e-03 -1.03420403e-03  3.76832462e-03  4.58832923e-03
 -4.34324611e-03  3.10382084e-03  1.00780977e-03  4.41145245e-03
 -5.12136845e-04  4.63267602e-03 -3.53350653e-03 -3.33461445e-03
 -7.83547061e-04  2.69262446e-03  1.10415494e-04  4.39082785e-03
 -4.17528907e-03 -3.94204585e-03 -1.05484365e-03  2.95000453e-03
 -8.84003704e-04 -4.03014477e-03  3.46649624e-03  2.64019845e-03
  9.21395782e-04 -4.00882

In [10]:
print(model['Bottle']) 

KeyError: ignored

In [ ]:
model.most_similar('Hello') #the vector of hello is compared with all other words

[('here', 0.08527158200740814),
 ('John', 0.07021407783031464),
 ('to', 0.06822391599416733),
 ('AI', 0.06018120050430298),
 ('DS', 0.05924709141254425),
 ('Program', 0.027920937165617943),
 ('have', 0.016009867191314697),
 ('you', 0.00652676448225975),
 ('Welcome', -0.008957228623330593),
 ('by', -0.018957197666168213)]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
model.most_similar('Apple') 

KeyError: ignored

## LP 

Here there is a big limitation where we need to train our model by our own from scratch. Model is not able to identify any new word. That is the disadvantage of when we train our own network

## -------------------------------------------------------

## Without Word2vec how can we create our own word embeddings?

##### Rescue is Keras. Keras embedding layer.

In [ ]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding

In [ ]:
#Define your own documents
sentences = ['Hello how are you',
             'how are you',
             'whats going on',
             'I am doing great',
             'You are awesome',
             'I really love you so much']

In [ ]:
sent_labels = array([1,1,1,0,0,0])

In [ ]:
vocab_size = 50 # dimension
encoded_sent = [one_hot(i,vocab_size)for i in sentences]
encoded_sent

[[34, 20, 35, 22],
 [20, 35, 22],
 [20, 43, 6],
 [1, 42, 22, 35],
 [22, 35, 20],
 [1, 36, 1, 22, 5, 35]]

In [ ]:
#Now I want my nn to train  for that the size of the vector should be same.
padded_sent = pad_sequences(encoded_sent,maxlen = 6,padding='pre')
print(padded_sent)

[[ 0  0 34 20 35 22]
 [ 0  0  0 20 35 22]
 [ 0  0  0 20 43  6]
 [ 0  0  1 42 22 35]
 [ 0  0  0 22 35 20]
 [ 1 36  1 22  5 35]]


In [ ]:
mymodel = Sequential()
mymodel.add(Embedding(vocab_size,8,input_length = 6,)) #6 senteences
mymodel.add(Flatten())
mymodel.add(Dense(1,activation = 'sigmoid')) #Because target is categorical in nature

In [ ]:
mymodel.compile(optimizer='adam',loss = 'binary_crossentropy',metrics = ['accuracy'])

In [ ]:
mymodel.fit(padded_sent,sent_labels,epochs = 30)

Epoch 1/30
1/1 [==============================] - 3s 3s/step - loss: 0.7062 - accuracy: 0.3333
Epoch 2/30
1/1 [==============================] - 0s 12ms/step - loss: 0.7037 - accuracy: 0.3333
Epoch 3/30
1/1 [==============================] - 0s 9ms/step - loss: 0.7013 - accuracy: 0.3333
Epoch 4/30
1/1 [==============================] - 0s 11ms/step - loss: 0.6989 - accuracy: 0.3333
Epoch 5/30
1/1 [==============================] - 0s 9ms/step - loss: 0.6965 - accuracy: 0.5000
Epoch 6/30
1/1 [==============================] - 0s 9ms/step - loss: 0.6942 - accuracy: 0.5000
Epoch 7/30
1/1 [==============================] - 0s 8ms/step - loss: 0.6918 - accuracy: 0.6667
Epoch 8/30
1/1 [==============================] - 0s 15ms/step - loss: 0.6895 - accuracy: 0.6667
Epoch 9/30
1/1 [==============================] - 0s 9ms/step - loss: 0.6872 - accuracy: 0.6667
Epoch 10/30
1/1 [==============================] - 0s 6ms/step - loss: 0.6848 - accuracy: 0.6667
Epoch 11/30
1/1 [====================

In [ ]:
#Evaluate the model
mymodel.evaluate(padded_sent,sent_labels,verbose = 1)

1/1 [==============================] - 0s 172ms/step - loss: 0.6366 - accuracy: 0.8333


[0.6365944147109985, 0.8333333134651184]

In [ ]:
model_loss,model_accuracy = mymodel.evaluate(padded_sent,sent_labels,verbose = 1)
print('Accuracy : %f' %(model_accuracy*100))

1/1 [==============================] - 0s 18ms/step - loss: 0.6366 - accuracy: 0.8333
Accuracy : 83.333331


### The Prediction part

In [ ]:
sent_for_pred = ['Hello how are you',
                 'I am doing great']

In [ ]:
vocab_size = 50 #Is it dimension?
encoded = [one_hot(i,vocab_size)for i in sent_for_pred]
encoded

[[34, 20, 35, 22], [1, 42, 22, 35]]

In [ ]:
#Now I want my nn to train  for that the size of the vector should be same.
padded_sent = pad_sequences(encoded,maxlen = 6,padding='pre')
print(padded_sent)

[[ 0  0 34 20 35 22]
 [ 0  0  1 42 22 35]]


In [ ]:
predict_x = mymodel.predict(padded_sent)
predict_x


array([[0.5358278 ],
       [0.48555127]], dtype=float32)

## LP
Hre vocab is so small, so model performance wont be that great.

## -------------------------------------------------------------

## 3. Using Pretrained Word2vec model

In [ ]:
from gensim.models import Word2Vec, KeyedVectors

In [ ]:
pretrained_model = KeyedVectors.load_word2vec_format('GoogleNews-vectors-negative300.bin',binary = True)

FileNotFoundError: ignored

In [ ]:
pretrained_model.most_similar('data')
print(result)