In [ ]:
!pip install flair

     |████████████████████████████████| 319 kB 4.9 MB/s 
     |████████████████████████████████| 19.7 MB 53.4 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
     |████████████████████████████████| 48 kB 5.3 MB/s 
     |████████████████████████████████| 1.2 MB 40.0 MB/s 
     |████████████████████████████████| 981 kB 38.6 MB/s 
     |████████████████████████████████| 64 kB 2.8 MB/s 
     |████████████████████████████████| 788 kB 43.1 MB/s 
     |████████████████████████████████| 59 kB 5.8 MB/s 
     |████████████████████████████████| 3.1 MB 40.6 MB/s 
     |████████████████████████████████| 62 kB 786 kB/s 
     |████████████████████████████████| 596 kB 47.1 MB/s 
     |████████████████████████████████| 3.3 MB 47.5 MB/s 
     |████████████████████████████████| 895 kB 44.3 MB/s 
  Created wheel for gdown: filename=gdown-3.12.2-py3-none-any.whl size=9704 sha256=6db7991a76e58a134fcd5beb749ba1b1285b82152e914

In [ ]:
import numpy as np
from flair.embeddings import WordEmbeddings
from flair.embeddings import TransformerWordEmbeddings
from flair.data import Sentence
from scipy.spatial import distance

# **Glove Embeddings Example**

In [ ]:
glove_embedding = WordEmbeddings('glove')
#We know that Word2Vec model creates vector for a word that is independent of the context. 
#ie, Numeric representation of a word will remain same irrespective of the context of a particular word.
#Glove is also a WordEmbedding model

2021-11-06 11:29:34,905 https://flair.informatik.hu-berlin.de/resources/embeddings/token/glove.gensim.vectors.npy not found in cache, downloading to /tmp/tmpphjl5qmm


100%|██████████| 160000128/160000128 [00:08<00:00, 19296628.06B/s]

2021-11-06 11:29:43,580 copying /tmp/tmpphjl5qmm to cache at /root/.flair/embeddings/glove.gensim.vectors.npy


2021-11-06 11:29:43,925 removing temp file /tmp/tmpphjl5qmm
2021-11-06 11:29:44,475 https://flair.informatik.hu-berlin.de/resources/embeddings/token/glove.gensim not found in cache, downloading to /tmp/tmpchm_z5gc


100%|██████████| 21494764/21494764 [00:01<00:00, 12742558.24B/s]

2021-11-06 11:29:46,576 copying /tmp/tmpchm_z5gc to cache at /root/.flair/embeddings/glove.gensim
2021-11-06 11:29:46,610 removing temp file /tmp/tmpchm_z5gc


In [ ]:
sentence_1 = Sentence("The founder of Apple is Steve Jobs")

In [ ]:
glove_embedding.embed(sentence_1)

[Sentence: "The founder of Apple is Steve Jobs"   [− Tokens: 7]]

In [ ]:
for token in sentence_1:
  print(token)
  print(token.embedding)
  print("\n")

Token: 1 The
tensor([-0.0382, -0.2449,  0.7281, -0.3996,  0.0832,  0.0440, -0.3914,  0.3344,
        -0.5755,  0.0875,  0.2879, -0.0673,  0.3091, -0.2638, -0.1323, -0.2076,
         0.3340, -0.3385, -0.3174, -0.4834,  0.1464, -0.3730,  0.3458,  0.0520,
         0.4495, -0.4697,  0.0263, -0.5415, -0.1552, -0.1411, -0.0397,  0.2828,
         0.1439,  0.2346, -0.3102,  0.0862,  0.2040,  0.5262,  0.1716, -0.0824,
        -0.7179, -0.4153,  0.2033, -0.1276,  0.4137,  0.5519,  0.5791, -0.3348,
        -0.3656, -0.5486, -0.0629,  0.2658,  0.3020,  0.9977, -0.8048, -3.0243,
         0.0125, -0.3694,  2.2167,  0.7220, -0.2498,  0.9214,  0.0345,  0.4674,
         1.1079, -0.1936, -0.0746,  0.2335, -0.0521, -0.2204,  0.0572, -0.1581,
        -0.3080, -0.4162,  0.3797,  0.1501, -0.5321, -0.2055, -1.2526,  0.0716,
         0.7056,  0.4974, -0.4206,  0.2615, -1.5380, -0.3022, -0.0734, -0.2831,
         0.3710, -0.2522,  0.0162, -0.0171, -0.3898,  0.8742, -0.7257, -0.5106,
        -0.5203, -0.1459,  

In [ ]:
sentence_1[0]

Token: 1 The

In [ ]:
sentence_1[1]

Token: 2 founder

In [ ]:
sentence_1[0].embedding

tensor([-0.0382, -0.2449,  0.7281, -0.3996,  0.0832,  0.0440, -0.3914,  0.3344,
        -0.5755,  0.0875,  0.2879, -0.0673,  0.3091, -0.2638, -0.1323, -0.2076,
         0.3340, -0.3385, -0.3174, -0.4834,  0.1464, -0.3730,  0.3458,  0.0520,
         0.4495, -0.4697,  0.0263, -0.5415, -0.1552, -0.1411, -0.0397,  0.2828,
         0.1439,  0.2346, -0.3102,  0.0862,  0.2040,  0.5262,  0.1716, -0.0824,
        -0.7179, -0.4153,  0.2033, -0.1276,  0.4137,  0.5519,  0.5791, -0.3348,
        -0.3656, -0.5486, -0.0629,  0.2658,  0.3020,  0.9977, -0.8048, -3.0243,
         0.0125, -0.3694,  2.2167,  0.7220, -0.2498,  0.9214,  0.0345,  0.4674,
         1.1079, -0.1936, -0.0746,  0.2335, -0.0521, -0.2204,  0.0572, -0.1581,
        -0.3080, -0.4162,  0.3797,  0.1501, -0.5321, -0.2055, -1.2526,  0.0716,
         0.7056,  0.4974, -0.4206,  0.2615, -1.5380, -0.3022, -0.0734, -0.2831,
         0.3710, -0.2522,  0.0162, -0.0171, -0.3898,  0.8742, -0.7257, -0.5106,
        -0.5203, -0.1459,  0.8278,  0.27

In [ ]:
sentence_1[0].embedding.shape #embedding shape

torch.Size([100])

# **Sentence 2**

In [ ]:
sentence_2 = Sentence("An Apple a day keeps a doctor away")

In [ ]:
glove_embedding.embed(sentence_2)

[Sentence: "An Apple a day keeps a doctor away"   [− Tokens: 8]]

In [ ]:
for token in sentence_2:
  print(token)
  print(token.embedding)
  print("\n")

Token: 1 An
tensor([-0.4214, -0.1880,  0.4624, -0.1761,  0.3621,  0.3670,  0.2792,  0.1463,
        -0.0542,  0.4583,  0.0654, -0.3372,  0.0675, -0.3632,  0.5030, -0.0104,
         0.7283, -0.1756, -0.3400,  0.0729,  0.6448, -0.2391,  0.3838,  0.1386,
         1.0994, -0.2488, -0.1508, -0.4874, -0.2304,  0.0648, -0.7018,  0.8265,
         0.0613,  0.1853, -0.3016, -0.0222,  0.3430,  0.8033,  0.1714,  0.1546,
        -0.5076,  0.3957,  0.0543, -0.5308,  0.4825,  0.0862,  0.5958, -0.2238,
        -0.3955, -0.7304, -0.1028, -0.3917,  1.2290,  1.2129, -1.0365, -3.4971,
         0.1092, -1.0084,  1.9998,  0.7964,  0.3881,  0.4375,  0.0852,  0.3855,
         0.6199, -1.0320,  0.7012, -0.2246,  0.0794,  0.0913, -0.2120, -0.5543,
        -0.0534, -0.8020,  0.4680, -0.0501, -0.5742, -0.0848, -1.7227, -0.9429,
         0.9867,  0.3121, -0.3774,  0.0687, -0.7784, -0.2849,  0.8105,  0.4660,
        -0.1186, -0.9341,  0.3372,  0.0379, -0.1827, -0.0199,  0.2049, -0.4772,
        -0.4925, -0.5652,  0

In [ ]:
sentence_2[1]

Token: 2 Apple

In [ ]:
sentence_2[1].embedding

tensor([-0.5985, -0.4632,  0.1300, -0.0196,  0.4603, -0.3018,  0.8977, -0.6563,
         0.6686, -0.4916,  0.0376, -0.0509,  0.6451, -0.5388, -0.3765, -0.0431,
         0.5138,  0.1778,  0.2860,  0.9206, -0.4935, -0.4858,  0.6132,  0.7821,
         0.1925,  0.9123, -0.0556, -0.1251, -0.6569,  0.0686,  0.5563,  1.6110,
        -0.0074, -0.4888,  0.4549,  0.9610, -0.0634,  0.1743,  0.9814, -1.3125,
        -0.1580, -0.5430, -0.1389, -0.2615, -0.3691,  0.2684, -0.2438, -0.1948,
         0.6258, -0.7377,  0.3835, -0.7500, -0.3905,  0.0915, -0.3659, -1.4715,
        -0.4523,  0.2256,  1.1412, -0.3853, -0.0672,  0.5729, -0.3919,  0.3130,
        -0.2923, -0.9616,  0.1515, -0.2166,  0.2510,  0.0970,  0.2843,  1.4296,
        -0.5056, -0.5137, -0.4722,  0.3204,  0.0231,  0.2262, -0.0972,  0.8213,
         0.9260, -1.0086, -0.3864,  0.8641, -1.2060, -0.2853,  0.2265, -0.3877,
         0.4088,  0.5930,  0.3077,  0.8380, -0.6366, -0.4464, -0.4341, -0.7936,
        -0.2867, -0.0344,  1.3431,  0.34

In [ ]:
sentence_2.embedding.shape

torch.Size([0])

# **Glove Distance between the same word**

In [ ]:
#Wkt, in sent_1 --> Apple is pointing towards an organization.
#And in sent_2 --> It is pointing towards an apple.

glove_dist = distance.euclidean(np.array(sentence_1[3].embedding),
                                np.array(sentence_2[1].embedding))
print("Distance between Apple embeddings for Glove = {}".format(glove_dist))

#Note: In GPU This script will never work

#TAKEAWAY : So Word2Vec Model dont understand the context of the word. To prove that hypothesis, we have taken the vectors representations of Apple in both the sentences.
#Lets calculate the euclidean distance of the word Apple in two sentences. 
#Zero difference. So Word2Vec is context independent. ie, never understand the context.

Distance between Apple embeddings for Glove = 0.0


# **bold text**

In [ ]:
bert_embedding = TransformerWordEmbeddings('bert-base-multilingual-cased')
bert_embedding

Downloading:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/625 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/972k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.87M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/681M [00:00<?, ?B/s]

TransformerWordEmbeddings(
  (model): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwi

In [ ]:
bert_embedding.embed(sentence_1)
for token in sentence_1:
  print(token)
  print(token.embedding)

Token: 1 The
tensor([-6.1165e-01, -3.6950e-01,  7.2882e-01, -1.6360e-01, -6.8383e-02,
        -3.1925e-01,  2.6473e-01, -4.4581e-01,  4.2001e-01,  9.0327e-01,
         6.9290e-01,  1.9871e-01,  5.5940e-01,  1.3097e-01,  7.2494e-01,
        -1.6668e-01, -2.9628e-01,  3.5229e-01,  3.0559e-01,  2.2671e-01,
        -1.9900e-01,  4.3672e-01, -6.1474e-01, -2.0876e-01, -3.3345e-01,
         9.6143e-02, -2.7794e-01,  1.0714e-01, -5.7169e-01,  9.5421e-01,
         3.4253e-01, -6.1661e-01,  2.6393e-01,  2.8641e-02, -5.0394e-01,
         2.0115e-01,  3.0094e-01,  2.3630e-01, -1.4445e-01, -3.2316e-01,
        -1.6605e-02, -6.8358e-01,  4.6748e-01,  1.4108e-01, -2.2300e-01,
        -6.8798e-01, -5.1986e-01, -8.0598e-02,  5.6592e-02, -4.8341e-01,
         3.1682e-01, -5.8784e-01, -7.5958e-02,  6.7899e-01,  2.0276e-01,
        -1.9120e-01,  1.2781e-01, -6.4472e-01,  2.7488e-01, -5.0320e-01,
         5.1696e-02, -3.5469e-01, -6.1651e-01,  2.0233e-01,  6.4425e-01,
         3.5971e-01,  6.9690e-01, -9.2

In [ ]:
sentence_1[0]

Token: 1 The

In [ ]:
sentence_1[0].embedding

tensor([-3.8194e-02, -2.4487e-01,  7.2812e-01, -3.9961e-01,  8.3172e-02,
         4.3953e-02, -3.9141e-01,  3.3440e-01, -5.7545e-01,  8.7459e-02,
         2.8787e-01, -6.7310e-02,  3.0906e-01, -2.6384e-01, -1.3231e-01,
        -2.0757e-01,  3.3395e-01, -3.3848e-01, -3.1743e-01, -4.8336e-01,
         1.4640e-01, -3.7304e-01,  3.4577e-01,  5.2041e-02,  4.4946e-01,
        -4.6971e-01,  2.6280e-02, -5.4155e-01, -1.5518e-01, -1.4107e-01,
        -3.9722e-02,  2.8277e-01,  1.4393e-01,  2.3464e-01, -3.1021e-01,
         8.6173e-02,  2.0397e-01,  5.2624e-01,  1.7164e-01, -8.2378e-02,
        -7.1787e-01, -4.1531e-01,  2.0335e-01, -1.2763e-01,  4.1367e-01,
         5.5187e-01,  5.7908e-01, -3.3477e-01, -3.6559e-01, -5.4857e-01,
        -6.2892e-02,  2.6584e-01,  3.0205e-01,  9.9775e-01, -8.0481e-01,
        -3.0243e+00,  1.2540e-02, -3.6942e-01,  2.2167e+00,  7.2201e-01,
        -2.4978e-01,  9.2136e-01,  3.4514e-02,  4.6745e-01,  1.1079e+00,
        -1.9358e-01, -7.4575e-02,  2.3353e-01, -5.2

In [ ]:
sentence_1[0].embedding.shape

torch.Size([868])

In [ ]:
bert_embedding.embed(sentence_2)
for token in sentence_2:
  print(token)
  print(token.embedding)

Token: 1 An
tensor([-1.9673e-01, -3.9774e-01, -2.6772e-01,  1.2102e-01, -4.3966e-01,
        -7.3569e-01, -1.9227e-01,  1.3942e-01, -4.1493e-01,  8.9477e-01,
         1.6197e+00, -3.6733e-01,  5.0971e-01,  6.5598e-01,  3.2974e-01,
        -8.9772e-02, -6.8056e-02,  2.7308e-01, -5.6996e-01,  3.2372e-01,
        -7.0598e-02, -4.0473e-01,  5.5125e-01,  8.9406e-01,  2.9831e-01,
         9.6198e-03,  1.2543e-01,  3.3899e-01, -4.5399e-01,  6.3205e-01,
         4.2390e-01,  2.2363e-01,  1.4975e-01,  2.3580e-01, -5.8375e-02,
         2.5523e-01,  1.2798e+00, -4.5175e-02, -3.6130e-01, -1.2531e+00,
        -1.2723e-01, -8.1958e-01, -2.3570e-01,  3.3164e-01,  5.7295e-02,
         4.4123e-01, -3.6829e-01, -2.5309e-01, -1.1801e-01, -5.1244e-01,
        -4.2216e-01, -3.0864e-01,  1.1219e-01,  4.6518e-01,  7.9430e-01,
        -2.0906e-01, -6.5522e-01, -1.4458e+00, -9.1990e-01,  1.4552e-01,
         6.3851e-01,  6.8153e-02, -1.2199e+00,  4.3694e-01,  3.5268e-01,
        -2.9992e-01, -1.8363e-02, -1.50

In [ ]:
sentence_2[1]

Token: 2 Apple

In [ ]:
sentence_2[1].embedding

tensor([-5.9850e-01, -4.6321e-01,  1.3001e-01, -1.9576e-02,  4.6030e-01,
        -3.0180e-01,  8.9770e-01, -6.5634e-01,  6.6858e-01, -4.9164e-01,
         3.7557e-02, -5.0889e-02,  6.4510e-01, -5.3882e-01, -3.7650e-01,
        -4.3120e-02,  5.1384e-01,  1.7783e-01,  2.8596e-01,  9.2063e-01,
        -4.9349e-01, -4.8583e-01,  6.1321e-01,  7.8211e-01,  1.9254e-01,
         9.1228e-01, -5.5596e-02, -1.2512e-01, -6.5688e-01,  6.8557e-02,
         5.5629e-01,  1.6110e+00, -7.3642e-03, -4.8879e-01,  4.5493e-01,
         9.6105e-01, -6.3369e-02,  1.7432e-01,  9.8140e-01, -1.3125e+00,
        -1.5801e-01, -5.4301e-01, -1.3888e-01, -2.6146e-01, -3.6910e-01,
         2.6844e-01, -2.4375e-01, -1.9484e-01,  6.2583e-01, -7.3770e-01,
         3.8351e-01, -7.5004e-01, -3.9053e-01,  9.1498e-02, -3.6591e-01,
        -1.4715e+00, -4.5228e-01,  2.2560e-01,  1.1412e+00, -3.8526e-01,
        -6.7160e-02,  5.7288e-01, -3.9191e-01,  3.1302e-01, -2.9235e-01,
        -9.6157e-01,  1.5154e-01, -2.1659e-01,  2.5

In [ ]:
sentence_2[0].embedding.shape

torch.Size([868])

In [ ]:
glove_dist = distance.euclidean(np.array(sentence_1[3].embedding),
                                np.array(sentence_2[1].embedding))
print("Distance between Apple embeddings for BERT = {}".format(glove_dist))

#So BERT is context dependent. The same word has different vectors based on the context.

Distance between Apple embeddings for Glove = 11.480239868164062
